[project]
name = "tp2"
version = "0.1.0"
description = "TP2 - Fundamentos de Inteligência Artificial (2026/2)"
readme = "README.md"
authors = [
    { name = "Pedro Brochado", email = "pedropsb95@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.11.2",
]

[build-system]
requires = ["uv_build>=0.11.16,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mypy>=2.3.1",
    "pytest>=9.1.1",
    "ruff>=0.16.8",
]

[tool.ruff]
line-length = 100
target-version = "py313"

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B"]

[tool.ruff.lint.isort]
known-first-party = ["tp2"]

[tool.mypy]
python_version = "3.13"
files = ["src"]
ignore_missing_imports = true
